#!/bin/bash
###############################################################################
# Copyright (C) 2010 Matan Nassau
#
# This file is part of INSPext.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################

###############################################################################
# Generate a main() function for CU unit-tests declared in a set of .h files.
#
# CU is a unit-testing framework for C; see http://cu.danfis.cz/
###############################################################################

OUT_PREFIX="test/" # by default
while getopts 'o:' OPT; do
  case $OPT in
    o) OUT_PREFIX=$(echo "$OPTARG" |sed 's/\/*$/\//')
    ;;
    ?) echo "Usage: $(basename $0) [-o out_prefix]" >&2
    ;;
  esac
done
shift $(($OPTIND - 1))

if [ $# -eq 0 ]; then
  echo "$(basename $0):Please specify at least one C header file to process." >&2
  echo "$(basename $0):For instance, try running $0 test_file.h" >&2
  exit -1
fi

FILENAMES=$*
for FILENAME in $FILENAMES; do
  if [ \! -f $FILENAME -o \! -r $FILENAME ]; then
    echo "$(basename $0):Can't find regular readable file $FILENAME" >&2
    exit -1
  fi
done

echo "/******************************************************************************
 * Copyright (C) 2010 Matan Nassau
 *
 * This file is part of INSPext.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/"
echo
echo "/* autogenerated code; edit at your own peril */"
echo
echo '#include <stdlib.h>'
echo '#include "cu.h"'
for FILENAME in $FILENAMES; do
  echo "#include \"$FILENAME\""
done
echo
echo 'TEST_SUITES {'
for FILENAME in $FILENAMES; do
  sed '/^TEST_SUITE(/ !d; s/TEST_SUITE/    &_ADD/; s/\s*{\s*$/,/;' $FILENAME
done
echo '    TEST_SUITES_CLOSURE'
echo '};'
echo
echo 'int main(int argc, char* argv[])'
echo '{'
echo "    CU_SET_OUT_PREFIX(\"$OUT_PREFIX\");"
echo '    CU_RUN(argc, argv);'
echo '    return EXIT_SUCCESS;'
echo '}'
