#!/bin/bash
###############################################################################
# Copyright (C) 2010 Matan Nassau
#
# This file is part of INSPext.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################

###############################################################################
# Generate a .h file corresponding to a given .c file consisting of CU tests.
#
# CU is a unit-testing framework for C; see http://cu.danfis.cz/
###############################################################################

if [ $# -eq 0 ]; then
  echo "Please specify a C implementation file to process." >&2
  echo "For instance, try running $0 test_file.c"
  exit -1
fi

filename=$1
if [ \! -f $filename -o \! -r $filename ]; then
  echo "Can't find regular readable file $filename" >&2
  exit -1
fi

name=$(basename $filename .c)

echo "/******************************************************************************
 * Copyright (C) 2010 Matan Nassau
 *
 * This file is part of INSPext.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/"
echo
echo "/* autogenerated code; edit at your own peril */"
echo
echo "#ifndef $(echo $name |tr a-z A-Z)_H_"
echo "#define $(echo $name |tr a-z A-Z)_H_"
echo
echo '#include "cu.h"'
echo
sed '/^TEST(/ !d; s/\s*{\?\s*$/;/;' <$filename
echo
echo "TEST_SUITE($(echo $name |sed 's/^test_\?//i')_suite) {"
sed '/^TEST(/ !d; s/^/    /; s/TEST/TEST_ADD/; s/\s*{\?\s*$/,/;' <$filename
echo "    TEST_SUITE_CLOSURE"
echo "};"
echo
echo "#endif /* $(echo $name |tr a-z A-Z)_H_ */"
