#!/bin/bash
###############################################################################
# Copyright (C) 2010 Matan Nassau
#
# This file is part of INSPext.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################

###############################################################################
# Generate a main() function for CU unit-tests declared in a set of .h files.
#
# CU is a unit-testing framework for C; see http://cu.danfis.cz/
###############################################################################

if [ $# -eq 0 ]; then
  echo "Please specify at least one C header file to process." >&2
  echo "For instance, try running $0 test_file.h"
  exit -1
fi

filenames=$*
for filename in $filenames; do
  if [ \! -f $filename -o \! -r $filename ]; then
    echo "Can't find regular readable file $filename" >&2
    exit -1
  fi
done

echo "/******************************************************************************
 * Copyright (C) 2010 Matan Nassau
 *
 * This file is part of INSPext.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/"
echo
echo "/* autogenerated code; edit at your own peril */"
echo
echo '#include <stdlib.h>'
echo '#include "cu.h"'
for filename in $filenames; do
  echo "#include \"$filename\""
done
echo
echo 'TEST_SUITES {'
for filename in $filenames; do
  sed '/^TEST_SUITE(/ !d; s/TEST_SUITE/    &_ADD/; s/\s*{\s*$/,/;' $filename
done
echo '    TEST_SUITES_CLOSURE'
echo '};'
echo
echo 'int main(int argc, char* argv[])'
echo '{'
echo '    CU_RUN(argc, argv);'
echo '    return EXIT_SUCCESS;'
echo '}'
