/* autogenerated code; edit at your own peril */

#include <stdlib.h>
#include "cu.h"
#include "test_string.h"

TEST_SUITES {
    TEST_SUITE_ADD(string_suite),
    TEST_SUITES_CLOSURE
};

int main(int argc, char* argv[])
{
    CU_RUN(argc, argv);
    return EXIT_SUCCESS;
}
