/******************************************************************************
 * Copyright (C) 2010 Matan Nassau
 *
 * This file is part of INSPext.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/

/* autogenerated code; edit at your own peril */

#include <stdlib.h>
#include "cu.h"
#include "test_string.h"

TEST_SUITES {
    TEST_SUITE_ADD(string_suite),
    TEST_SUITES_CLOSURE
};

int main(int argc, char* argv[])
{
    CU_SET_OUT_PREFIX("test/regressions/");
    CU_RUN(argc, argv);
    return EXIT_SUCCESS;
}
