#ifndef TEST_STRING_H_
#define TEST_STRING_H_

#include "cu.h"

/* autogenerated code; edit at your own peril */

TEST(strichr_lowercase);
TEST(strichr_fail);
TEST(strichr_uppercase);
TEST(strnicmp_same_case);
TEST(strnicmp_different_case);

TEST_SUITE(string_suite) {
    TEST_ADD(strichr_lowercase),
    TEST_ADD(strichr_fail),
    TEST_ADD(strichr_uppercase),
    TEST_ADD(strnicmp_same_case),
    TEST_ADD(strnicmp_different_case),
    TEST_SUITE_CLOSURE
};

#endif /* TEST_STRING_H_ */
