#! /usr/bin/env python

import Options, Utils

def post(ctx):
    Utils.exec_command('build/default/test/check')

def build(bld):
    bld.add_post_fun(post)
    bld.new_task_gen(
        features = 'cc cprogram test',
        source = bld.path.ant_glob('*.c'),
        ccflags = ['-Wall', '-ansi', '-pedantic', '-g3'],
        add_objects = 'objs',
        target = 'check')
